enum CoachingTips {
    static let all: [String] = [
        "Triangulate — always give the ball carrier two passing options.",
        "Ground balls win games. Practice scooping from both sides every day.",
        "Spacing is everything — keep players 10–15 yards apart.",
        "Defensive slides start before the ball moves, not after.",
        "Goalie communication is the engine of your defense. Train it early.",
        "Clear the ball fast — quick clears create fast-break opportunities.",
        "Midfielders: always have your stick in your outside hand when defending.",
        "Teach players to feed, not just shoot — unselfish play creates open looks.",
        "Pick-and-roll fundamentals from basketball transfer directly to lacrosse.",
        "Short restarts beat zone defenses — push pace before the defense sets.",
        "Off-ball movement matters as much as on-ball skill.",
        "Help defenders recover by communicating early: 'I've got your back.'",
        "On a fast break, take one extra step closer before shooting.",
        "Winning the face-off consistently can swing a close game by three possessions.",
        "Always have a player behind the crease on offensive set plays.",
        "Attack players: practice finishing with your off-hand — defenders will force it.",
        "Zone offense: move the zone, don't move into the zone.",
        "Low-to-high passes create better angles and avoid body checks.",
        "Defensive positioning: body between the ball and the crease, always.",
        "Transition offense: push numbers, not just the ball.",
        "Cradling too much slows you down — minimize wrist action at full speed.",
        "Silent defenses are broken defenses. Encourage constant talk.",
        "Midfielders must get back on defense before the other team gets set.",
        "Drill all three face-off techniques: scoop, clamp, and rake.",
        "Extra-man offense: move the ball to move their feet, then shoot.",
        "Man-down defense: stay disciplined, protect the crease, force outside shots.",
        "A full crease attack creates inside opportunities — don't leave it empty.",
        "Shot placement beats shot power at youth levels — corners win games.",
        "Practice unsettled situations: clears, fast-breaks, and man-up/man-down.",
        "Winning the ground ball is a mindset, not just a skill.",
        "Trust the rotation — individual heroics in team sports usually backfire.",
        "On a screen, watch the goalie's hands — not the ball.",
        "Teach players to release under pressure rather than holding and getting stripped.",
        "Defensive footwork: don't reach — stay between your player and the goal.",
        "Get to every ground ball with your body low and your stick out front.",
        "Positive reinforcement in the first moment after a mistake makes the next attempt better.",
        "At youth levels, maximum touches beats complex systems.",
        "Half-time adjustments should be simple: one or two changes, not ten.",
        "A rotation plan reduces decision fatigue for everyone on the sideline.",
        "Hustle stats tell the real story: ground balls, caused turnovers, saves.",
        "Model calm composure — it teaches more than any drill.",
        "Offensive possession time directly reduces defensive breakdowns.",
        "Make practice harder than the game and the game will feel easy.",
        "Short-stick midfielders need to be your best athletes — they cover the most ground.",
        "Clear to the sideline, not up the gut — gut clears create turnovers.",
        "After every sub, the new player should immediately communicate to teammates.",
        "Practice the ride hard — a successful ride is worth a full possession.",
        "Quick drops and shuffles win checks at the crease — slow feet lose.",
        "Celebrate effort as loudly as you celebrate goals.",
        "Keep your stick in a ready position when approaching the goal.",
    ]
}
